

export const listImagePaths = [
    // "./model/arm_d.png",
    // "./model/arm_n.png",
    // "./model/arm_r.png",
    // "./model/bikini_n.png",
    // "./model/bikini_r.png",
    // "./model/body_d.png",
    // "./model/body_n.png",
    // "./model/body_r.png",
    // "./model/dress_Base_Color_black.png",
    // "./model/dress_Base_Color_line.png",
    // "./model/dress_Base_Color_red.png",
    // "./model/dress_Base_Color_white.png",
    // "./model/dress_Normal.png",
    // "./model/dress_Roughness.png",
    // "./model/eye_d.png",
    // "./model/eye_n.png",
    // "./model/eye_r.png",
    // "./model/eyelash.png",
    // "./model/gen_d.png",
    // "./model/gen_n.png",
    // "./model/gen_r.png",
    // "./model/hair_d.png",
    // "./model/hair_n.png",
    // "./model/head_d.png",
    // "./model/head_n.png",
    // "./model/head_r.png",
    // "./model/leg_d.png",
    // "./model/leg_n.png",
    // "./model/leg_r.png",
    // "./model/mouth_d.png",
    // "./model/mouth_m.png",
    // "./model/mouth_n.png",
    // "./model/skirt_Base_Color_black.png",
    // "./model/skirt_Base_Color_red.png",
    // "./model/skirt_Normal.png",
    // "./model/skirt_Roughness.png",
    "./model/tex.png",
]